### ISSUE TITLE
Homebrew install growly no longer works

### ISSUE THREAD

**Issue by tomten** [ryankee/growly#1]
In homebrew, growly is dependent on growlnotify, which no longer exists in homebrew. Therefore brew install growly just gives Error: No available formula for growlnotify.

**Comment by ryankee** [comment]
Changed my mind on removing growly from homebrew. I'm leaving it in homebrew but removing the growlnotify dependency. The user is now responsible for installing Growl on their own.

https://github.com/ryankee/growly/commit/6351793c8d2c39975fbb41572e6fe225904a452c
